---
- name: Apply Hardening on all hosts
  hosts: all
  become: true
  vars:
    # Default variables (can be overridden)
    ssh_port: 22
    ssh_allowed_users: []

  roles:
    - role: users
      tags: ['users', 'setup']

    - role: sshd
      tags: ['ssh', 'security', 'anssi']
    
    - role: hardening
      tags: ['sysctl', 'updates', 'security', 'anssi']
